"use client"
import './globals.css'
import { Inter } from 'next/font/google'

import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import Header from './view/AdminLayOut/Header/page'
import Footer from './view/AdminLayOut/Footer/page'



const queryClient = new QueryClient()


// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <QueryClientProvider client={queryClient}>
        <body >
      
       {/* <Header></Header> */}
          {children}
          {/* <Footer></Footer> */}
        </body>
      </QueryClientProvider>


    </html>
  )
}
